config/routes.rb
Rails.application.routes.draw do
  resources :schedules
  resources :sections
  resources :classrooms
  resources :teachers do
    resources :teacher_subjects, shallow: true
  end
  resources :subjects
  root to: 'subjects#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/teacher_subject.rb
class TeacherSubject < ApplicationRecord
  DEFAULT_LEVEL = 5

  belongs_to :teacher
  belongs_to :subject

  validates :teacher, uniqueness: {scope: :subject}, if: :_not_marked_for_destruction?

  validates :level, presence: true, numericality: { only_integer: true }
  before_validation :_default_values_on_create, on: :create

  def _default_values_on_create
    self.level ||= DEFAULT_LEVEL
    # return value should be true or nil
    true
  end

  def _not_marked_for_destruction?
    # Rails validation does not work well when we update subject with
    # teacher_subjects_attributes when we mark_for_destruction
    subject.teacher_subjects.none?(&:_destroy)
  end
end

app/controllers/teacher_subjects_controller.rb
class TeacherSubjectsController < ApplicationController
  before_action :_set_teacher_subject, only: %i[show edit update destroy]
  before_action :_set_teacher, only: %i[new create]

  def edit; end

  def show; end

  def update
    if @teacher_subject.update(_teacher_subject_params)
      render :show
    else
      render :edit
    end
  end

  def new
    @teacher_subject = TeacherSubject.new level: TeacherSubject::DEFAULT_LEVEL
  end

  def create
    @teacher_subject = TeacherSubject.new _teacher_subject_params
    @teacher_subject.teacher = @teacher
    if @teacher_subject.save
      flash[:notice] = 'Class was successfully added'
    else
      render :new
    end
  end

  def destroy
    @teacher_subject.destroy!
    flash[:notice] = 'Class was successfully removed'
  end

  private

  def _set_teacher_subject
    @teacher_subject = TeacherSubject.find params[:id]
  end

  def _set_teacher
    @teacher = Teacher.find params[:teacher_id]
  end

  def _teacher_subject_params
    params.require(:teacher_subject).permit(:level, :subject_id)
  end
end

app/views/teacher_subjects/_create_form.html.erb
<div id='new-teacher-subject'>
  <%= semantic_form_for(
    @teacher_subject,
    url: teacher_teacher_subjects_path(@teacher),
    remote: true
  ) do |form| %>
    <%= render 'shared/errors', model: @teacher_subject, name: 'Teacher' %>

    <div class="field">
      <%= form.label :subject, class: :label %>
      <%= form.input :subject, as: :select,
        collection: Subject.where.not(id: @teacher.subjects),
        label: false,
        wrapper_html: { tag: 'div', class: '' },
        input_html: { class: 'input' }
      %>
    </div>

    <div class="field">
      <%= form.label :level, class: :label %>
      <%= form.input :level, as: :number, label: false, wrapper_html: { tag: 'div', class: '' }, input_html: { class: 'input' } %>
    </div>

    <div class="actions">
      <%= form.submit 'Add' %>
    </div>
  <% end %>
</div>

app/views/teacher_subjects/_form.html.erb
<div id='teacher-subject-<%= @teacher_subject.id %>'>
  <%= semantic_form_for(@teacher_subject, remote: true) do |form| %>
    <%= render 'shared/errors', model: @teacher_subject, name: 'Teacher' %>

    <div class="field">
      <%= form.input :level, as: :number, wrapper_html: { tag: 'div', class: '' }, input_html: { class: 'input' } %>
    </div>

      <%= form.submit 'Update', class: 'button is-warning' %>
      <%= link_to 'Remove', teacher_subject_path(@teacher_subject), remote: true, method: :delete, class: 'button is-danger', data: { confirm: 'Are you sure?' } %>
      <%= link_to 'Cancel', teacher_subject_path(@teacher_subject), remote: true, class: 'button is-success' %>
  <% end %>
</div>

app/views/teacher_subjects/_new.html.erb
<div id='new-teacher-subject'>
  <% if @teacher.subjects.size < Subject.all.size %>
    <%= link_to 'Add new class', new_teacher_teacher_subject_path(@teacher), remote: true, class: 'button is-success' %>
  <% else %>
    Please <%= link_to 'create new classes', new_subject_path, class: 'has-text-link' %> so you can add to Teacher
  <% end %>
</div>

app/views/teacher_subjects/_show.html.erb
<li id='teacher-subject-<%= teacher_subject.id %>'>
  <%= link_to teacher_subject.subject.name, subject_path(teacher_subject.subject) %> (<%= teacher_subject.level %>)
  <%= link_to 'Edit', edit_teacher_subject_path(teacher_subject), remote: true %>
</li>

app/views/teacher_subjects/create.js.erb
window.location.reload()

app/views/teacher_subjects/destroy.js.erb
var el = document.getElementById('teacher-subject-<%= @teacher_subject.id %>')
el.classList.add('hide');
el.classList.remove('show');
setTimeout(function() {
  window.location.reload()
}, 400);

app/views/teacher_subjects/edit.js.erb
document.getElementById('teacher-subject-<%= @teacher_subject.id %>').outerHTML = '<%= j render 'form' %>'

app/views/teacher_subjects/new.js.erb
document.getElementById('new-teacher-subject').outerHTML = '<%= j render 'create_form' %>'

app/views/teacher_subjects/show.js.erb
document.getElementById('teacher-subject-<%= @teacher_subject.id %>').outerHTML = '<%= j render 'teacher_subjects/show', teacher_subject: @teacher_subject %>'