config/routes.rb
Rails.application.routes.draw do
  resources :schedules
  resources :sections
  resources :classrooms
  resources :teachers do
    resources :teacher_subjects, shallow: true
  end
  resources :subjects
  root to: 'subjects#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/schedule.rb
class Schedule < ApplicationRecord
  belongs_to :student
  belongs_to :section
end

app/controllers/schedules_controller.rb
class SchedulesController < ApplicationController
  before_action :set_schedule, only: [:show, :edit, :update, :destroy]

  # GET /schedules
  # GET /schedules.json
  def index
    @schedules = Schedule.all
  end

  # GET /schedules/1
  # GET /schedules/1.json
  def show
  end

  # GET /schedules/new
  def new
    @schedule = Schedule.new
  end

  # GET /schedules/1/edit
  def edit
  end

  # POST /schedules
  # POST /schedules.json
  def create
    @schedule = Schedule.new(schedule_params)

    begin
      @schedule.save
    rescue => e
      @schedule.errors.add(:base, e.message)
    end

    respond_to do |format|
      if @schedule.errors.empty?
        format.html { redirect_to @schedule, notice: 'Schedule was successfully created.' }
        format.json { render :show, status: :created, location: @schedule }
      else
        format.html { render :new }
        format.json { render json: @schedule.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /schedules/1
  # PATCH/PUT /schedules/1.json
  def update
    begin
      @schedule.update!(schedule_params)
    rescue => e
      @schedule.errors.add(:base, e.message)
    end

    respond_to do |format|
      if @schedule.errors.empty?
        format.html { redirect_to @schedule, notice: 'Schedule was successfully updated.' }
        format.json { render :show, status: :ok, location: @schedule }
      else
        format.html { render :edit }
        format.json { render json: @schedule.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /schedules/1
  # DELETE /schedules/1.json
  def destroy
    @schedule.destroy
    respond_to do |format|
      format.html { redirect_to schedules_url, notice: 'Schedule was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_schedule
      @schedule = Schedule.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def schedule_params
      params.require(:schedule).permit(:student_id, :section_id)
    end
end

app/helpers/schedules_helper.rb
module SchedulesHelper
end

app/views/schedules/_form.html.erb
<%= semantic_form_for(schedule) do |form| %>
  <%= render 'shared/errors', model: schedule, name: 'Section' %>

  <div class="field select is-multiple">
    <%= form.label :student_id, class: :label %>
    <%= form.input :student, label: false, as: :select,
      wrapper_html: { tag: 'div', class: '' } %>
  </div>

  <div class="field select is-multiple">
    <%= form.label :classroom, class: :label %>
    <%= form.input :section,
      label: false,
      as: :select,
      wrapper_html: { tag: 'div', class: '' }
    %>
  </div>

  <div class="actions">
    <%= form.submit class: 'button is-danger' %>
  </div>
<% end %>

app/views/schedules/edit.html.erb
<h1 class="title">Editing Schedule</h1>

<%= render 'form', schedule: @schedule %>

<%= link_to 'Show', @schedule, class: 'button is-info' %>
<%= link_to 'Back', schedules_path, class: 'button is-info' %>

app/views/schedules/index.html.erb
<%= render 'shared/notice' %>

<h1 class="title">Schedules</h1>

<table class="table is-bordered is-striped">
  <thead>
    <tr>
      <th>Student</th>
      <th>Section</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @schedules.each do |schedule| %>
      <tr>
        <td><%= schedule.student %></td>
        <td><%= schedule.section %></td>
        <td><%= link_to 'Show', schedule %></td>
        <td><%= link_to 'Edit', edit_schedule_path(schedule) %></td>
        <td><%= link_to 'Destroy', schedule, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Schedule', new_schedule_path, class: 'button is-link' %>

app/views/schedules/new.html.erb
<h1 class="title">New Schedule</h1>

<%= render 'form', schedule: @schedule %>

<%= link_to 'Back', schedules_path, class: 'button is-link' %>

app/views/schedules/show.html.erb
<%= render 'shared/notice' %>

<div class="box">
  <div class="field">
    <p class="label">Student:</p>
    <div class="control">
      <%= @schedule.student %>
    </div>
  </div>

  <div class="field">
    <p class="label">Section:</p>
    <div class="control">
      <%= @schedule.section %>
    </div>
  </div>

  <%= link_to 'Edit', edit_schedule_path(@schedule), class: 'button is-link' %>
  <%= link_to 'Back', schedules_path, class: 'button is-link' %>

</div>