config/routes.rb
Rails.application.routes.draw do
  resources :schedules
  resources :sections
  resources :classrooms
  resources :teachers do
    resources :teacher_subjects, shallow: true
  end
  resources :subjects
  root to: 'subjects#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/subject.rb
class Subject < ApplicationRecord
  has_many :teacher_subjects, dependent: :destroy
  has_many :teachers, through: :teacher_subjects
  accepts_nested_attributes_for :teacher_subjects, allow_destroy: true

  validates :name, presence: true
end

app/controllers/subjects_controller.rb
class SubjectsController < ApplicationController
  before_action :set_subject, only: %i[show edit update destroy]

  # GET /subjects
  # GET /subjects.json
  def index
    @subjects = Subject.all
  end

  # GET /subjects/1
  # GET /subjects/1.json
  def show; end

  # GET /subjects/new
  def new
    @subject = Subject.new
  end

  # GET /subjects/1/edit
  def edit; end

  # POST /subjects
  # POST /subjects.json
  def create
    @subject = Subject.new(subject_params.merge(teacher_subjects_params))

    respond_to do |format|
      if @subject.save
        format.html { redirect_to @subject, notice: 'Class was successfully created.' }
        format.json { render :show, status: :created, location: @subject }
      else
        format.html { render :new }
        format.json { render json: @subject.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /subjects/1
  # PATCH/PUT /subjects/1.json
  def update
    respond_to do |format|
      if @subject.update(subject_params.merge(teacher_subjects_params))
        format.html { redirect_to @subject, notice: 'Class was successfully updated.' }
        format.json { render :show, status: :ok, location: @subject }
      else
        format.html { render :edit }
        format.json { render json: @subject.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /subjects/1
  # DELETE /subjects/1.json
  def destroy
    @subject.destroy
    respond_to do |format|
      format.html { redirect_to subjects_url, notice: 'Class was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_subject
    @subject = Subject.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def subject_params
    params.require(:subject).permit(
      :name,
      :description,
      :teacher_ids
    )
  end

  def teacher_subjects_params
    return {} if params[:subject][:teacher_ids].nil?

    @subject.teacher_subjects.each(&:mark_for_destruction) if @subject.present?
    {
      teacher_subjects_attributes: params[:subject][:teacher_ids].reject(&:empty?).map { |id| {teacher_id: id} }
    }
  end
end

app/helpers/subjects_helper.rb
module SubjectsHelper
end

app/views/subjects/_form.html.erb
<%= semantic_form_for(subject) do |form| %>
  <%= render 'shared/errors', model: subject, name: 'Class' %>

  <div class="field">
    <%= form.label :name, class: :label %>
    <div class="control">
      <%= form.text_field :name, class: :input %>
    </div>
  </div>

  <div class="field">
    <%= form.label :description, class: :label %>
    <%= form.text_area :description, class: :textarea %>
  </div>

  <div class='field select is-multiple'>
    <%= form.label :teachers, class: :label %>
    <%= form.input :teachers,label: false, as: :select,
      multiple: true,
      include_blank: false,
      wrapper_html: { tag: 'div' }
    %>
  </div>

  <div class="actions">
    <%= form.submit class: 'button is-danger' %>
  </div>
<% end %>

app/views/subjects/edit.html.erb
<h1 class="title">Editing Class</h1>

<%= render 'form', subject: @subject %>

<%= link_to 'Show', @subject, class: 'button is-info' %>
<%= link_to 'Back', subjects_path, class: 'button is-info' %>

app/views/subjects/index.html.erb
<%= render 'shared/notice' %>

<h1 class="title">Classes</h1>

<table class="table is-bordered is-striped">
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @subjects.each do |subject| %>
      <tr>
        <td><%= subject.name %></td>
        <td><%= subject.description %></td>
        <td><%= link_to 'Show', subject %></td>
        <td><%= link_to 'Edit', edit_subject_path(subject) %></td>
        <td><%= link_to 'Destroy', subject, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Class', new_subject_path, class: 'button is-link' %>

app/views/subjects/new.html.erb
<h1 class="title">New Class</h1>

<%= render 'form', subject: @subject %>

<%= link_to 'Back', subjects_path, class: 'button is-link' %>

app/views/subjects/show.html.erb
<%= render 'shared/notice' %>

<div class="box">
  <div class="field">
    <p class="label">Name:</p>
    <div class="control">
      <%= @subject.name %>
    </div>
  </div>

  <div class="field">
    <p class="label">Description:</p>
    <div class="control">
      <%= @subject.description %>
    </div>
  </div>

  <div class="field">
    <p class="label">Teachers:</p>
    <div class="control content">
      <ul class="is-medium">
        <% @subject.teacher_subjects.each do |teacher_subject| %>
          <li><%= link_to teacher_subject.teacher.first_and_last_name, teacher_path(teacher_subject.teacher), class: 'link' %></li>
        <% end %>
      </ul>
    </div>
  </div>

  <%= link_to 'Edit', edit_subject_path(@subject), class: 'button is-link' %>
  <%= link_to 'Back', subjects_path, class: 'button is-link' %>
</div>