config/routes.rb
Rails.application.routes.draw do
  resources :schedules
  resources :sections
  resources :classrooms
  resources :teachers do
    resources :teacher_subjects, shallow: true
  end
  resources :subjects
  root to: 'subjects#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/teacher.rb
class Teacher < ApplicationRecord
  has_many :teacher_subjects
  has_many :sections
  has_many :subjects, through: :teacher_subjects
  accepts_nested_attributes_for :teacher_subjects, allow_destroy: true

  validates :first_name, :last_name, presence: true

  def first_and_last_name
    "#{first_name} #{last_name}"
  end
  alias_method :to_s, :first_and_last_name
end

app/controllers/teachers_controller.rb
class TeachersController < ApplicationController
  before_action :set_teacher, only: %i[show edit update destroy]

  # GET /teachers
  # GET /teachers.json
  def index
    @teachers = Teacher.all
  end

  # GET /teachers/1
  # GET /teachers/1.json
  def show; end

  # GET /teachers/new
  def new
    @teacher = Teacher.new
  end

  # GET /teachers/1/edit
  def edit; end

  # POST /teachers
  # POST /teachers.json
  def create
    @teacher = Teacher.new(teacher_params)

    respond_to do |format|
      if @teacher.save
        format.html { redirect_to @teacher, notice: 'Teacher was successfully created.' }
        format.json { render :show, status: :created, location: @teacher }
      else
        format.html { render :new }
        format.json { render json: @teacher.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /teachers/1
  # PATCH/PUT /teachers/1.json
  def update
    respond_to do |format|
      if @teacher.update(teacher_params)
        format.html { redirect_to @teacher, notice: 'Teacher was successfully updated.' }
        format.json { render :show, status: :ok, location: @teacher }
      else
        format.html { render :edit }
        format.json { render json: @teacher.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /teachers/1
  # DELETE /teachers/1.json
  def destroy
    @teacher.destroy
    respond_to do |format|
      format.html { redirect_to teachers_url, notice: 'Teacher was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_teacher
    @teacher = Teacher.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def teacher_params
    params.require(:teacher).permit(:first_name, :last_name)
  end
end

app/helpers/teachers_helper.rb
module TeachersHelper
end

app/views/teachers/_form.html.erb
<%= semantic_form_for(teacher) do |form| %>
  <%= render 'shared/errors', model: teacher, name: 'Teacher' %>

  <div class="field">
    <%= form.label :first_name, class: :label %>
    <div class="control">
      <%= form.input :first_name, label: false, wrapper_html: { tag: 'div', class: '' }, input_html: { class: 'input' } %>
    </div>
  </div>

  <div class="field">
    <%= form.label :last_name, class: :label %>
    <div class="control">
      <%= form.input :last_name, label: false, wrapper_html: { tag: 'div', class: '' }, input_html: { class: 'input' } %>
    </div>
  </div>

  <div class="actions">
    <%= form.submit class: 'button is-danger' %>
  </div>
<% end %>

app/views/teachers/edit.html.erb
<h1 class="title">Editing Teacher</h1>

<%= render 'form', teacher: @teacher %>

<%= link_to 'Show', @teacher, class: 'button is-info' %>
<%= link_to 'Back', teachers_path, class: 'button is-info' %>

app/views/teachers/index.html.erb
<%= render 'shared/notice' %>

<h1 class="title">Teachers</h1>

<table class="table is-bordered is-striped">
  <thead>
    <tr>
      <th>First name</th>
      <th>Last name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @teachers.each do |teacher| %>
      <tr>
        <td><%= teacher.first_name %></td>
        <td><%= teacher.last_name %></td>
        <td><%= link_to 'Show', teacher %></td>
        <td><%= link_to 'Edit', edit_teacher_path(teacher) %></td>
        <td><%= link_to 'Destroy', teacher, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Teacher', new_teacher_path, class: 'button is-link' %>

app/views/teachers/new.html.erb
<h1 class="title">New Teacher</h1>

<%= render 'form', teacher: @teacher %>

<%= link_to 'Back', teachers_path, class: 'button is-link' %>

app/views/teachers/show.html.erb
<%= render 'shared/notice' %>

<div class="box">
  <div class="field">
    <p class="label">First name:</p>
    <div class="control">
      <%= @teacher.first_name %>
    </div>
  </div>

  <div class="field">
    <p class="label">Last name:</p>
    <div class="control">
      <%= @teacher.last_name %>
    </div>
  </div>

  <div class="field">
    <%= link_to 'Edit', edit_teacher_path(@teacher), class: 'button is-link' %>
    <%= link_to 'Back', teachers_path, class: 'button is-link' %>
  </div>

  <div class="field">
    <p class="label">Classes</p>
    <div class="control content">
      <ul class="is-medium">
        <% @teacher.teacher_subjects.each do |teacher_subject| %>
          <%= render 'teacher_subjects/show', teacher_subject: teacher_subject %>
        <% end %>
      </ul>
      <%= render 'teacher_subjects/new' %>
    </div>
  </div>
</div>